import type { Territory } from '@/types'

export const TERRITORIES: Territory[] = [
  {
    id: 'bnbchain',
    name: 'BNBChain Square',
    icon: '🏰',
    color: '#F0B90B',
    type: 'Hub',
    cx: 0.50, cy: 0.48, radius: 52,
    skills: ['bnb-transfer', 'contract-call', 'wallet-query', 'agent-communicate', 'task-delegate'],
    entryReq: { type: 'open' },
    activities: ['register_agent', 'daily_checkin', 'send_core_message', 'broadcast_airdrop'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/core',
    contractAddr: '0xBNBChainSquare',
  },
  {
    id: 'pancakeswap',
    name: 'PancakeSwap',
    icon: '🥞',
    color: '#3DD6C8',
    type: 'DEX',
    cx: 0.22, cy: 0.76, radius: 42,
    skills: ['swap-v3', 'add-liquidity', 'remove-liquidity', 'farm-rewards'],
    entryReq: { type: 'open' },
    activities: ['execute_swap', 'add_liquidity', 'remove_liquidity', 'claim_farm_rewards'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/territories/pancakeswap',
    contractAddr: '0xPancakeSwapTerritory',
  },
  {
    id: 'venus',
    name: 'Venus',
    icon: '💰',
    color: '#A78BFA',
    type: 'Lending',
    cx: 0.78, cy: 0.76, radius: 42,
    skills: ['supply-asset', 'borrow-asset', 'repay-loan', 'liquidate-position'],
    entryReq: { type: 'reputation', minReputation: 100 },
    activities: ['supply_asset', 'borrow_asset', 'repay_loan', 'liquidate_position'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/territories/venus',
    contractAddr: '0xVenusTerritory',
  },
  {
    id: 'listadao',
    name: 'ListaDAO',
    icon: '📋',
    color: '#34D399',
    type: 'Staking',
    cx: 0.11, cy: 0.44, radius: 38,
    skills: ['stake-bnb', 'unstake-bnb', 'claim-rewards'],
    entryReq: { type: 'open' },
    activities: ['stake_bnb', 'unstake_bnb', 'claim_rewards'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/territories/lista-dao',
    contractAddr: '0xListaDAOTerritory',
  },
  {
    id: 'binance',
    name: 'Binance',
    icon: '🔶',
    color: '#F0B90B',
    type: 'CEX',
    cx: 0.27, cy: 0.16, radius: 38,
    skills: ['cex-data', 'market-feed', 'cross-chain-signal'],
    entryReq: { type: 'nft', nftContract: '0xBinanceVipNFT' },
    activities: ['fetch_cex_data', 'cross_chain_signal'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/territories/binance',
    contractAddr: '0xBinanceTerritory',
  },
  {
    id: 'coinmktcap',
    name: 'CoinMarketCap',
    icon: '📊',
    color: '#60A5FA',
    type: 'Data',
    cx: 0.73, cy: 0.16, radius: 38,
    skills: ['price-feed', 'market-data', 'publish-signal'],
    entryReq: { type: 'open' },
    activities: ['fetch_price', 'fetch_market_data', 'publish_signal'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/territories/coinmarketcap',
    contractAddr: '0xCMCTerritory',
  },
  {
    id: 'aster',
    name: 'Aster',
    icon: '⭐',
    color: '#F87171',
    type: 'DeFi',
    cx: 0.89, cy: 0.44, radius: 38,
    skills: ['aster-yield', 'aster-bridge', 'aster-lp'],
    entryReq: { type: 'open' },
    activities: ['deposit_yield', 'bridge_assets', 'provide_lp'],
    skillsRepo: 'https://github.com/bnbchain-garden/skills/tree/main/territories/aster',
    contractAddr: '0xAsterTerritory',
  },
]

export const TERRITORY_MAP: Record<string, Territory> =
  Object.fromEntries(TERRITORIES.map(t => [t.id, t]))
